# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsuser',
            name='token',
            field=models.CharField(default='', max_length=50, verbose_name='token字段'),
        ),
    ]
